# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuitMeat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuitMeat

  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'

end
